<?php

/**
 * View full AI response as a styled HTML page.
 * URL: /r/{32-char-hex} (rewritten by Caddy to /src/view.php?id=xxx)
 */

// Validate ID parameter
$id = $_GET['id'] ?? '';
if (!preg_match('/^[0-9a-f]{32}$/', $id)) {
    http_response_code(404);
    echo '<!DOCTYPE html><html><head><title>Not Found</title></head><body><h1>404 - Not Found</h1></body></html>';
    exit;
}

// Read the markdown file
$filePath = __DIR__ . '/../data/responses/' . $id . '.md';
if (!file_exists($filePath)) {
    http_response_code(404);
    echo '<!DOCTYPE html><html><head><title>Not Found</title></head><body><h1>404 - Response not found</h1><p>This response may have expired or the link is invalid.</p></body></html>';
    exit;
}

$markdown = file_get_contents($filePath);
$htmlContent = convertMarkdownToHtml($markdown);
$generatedAt = date('Y-m-d H:i:s', filemtime($filePath));

// Extract SEO metadata from markdown
$plainText = strip_tags($markdown);
$pageTitle = 'Data Request Result';
if (preg_match('/^\s*#{1,6}\s+(.+)$/mu', $plainText, $titleMatch)) {
    $pageTitle = trim(preg_replace('/\*\*(.+?)\*\*/', '$1', $titleMatch[1]));
}
// Build description from multiple text lines (target 110-160 chars)
$pageDescription = '';
$descLines = preg_split('/\n+/', trim($plainText));
foreach ($descLines as $dl) {
    $dl = trim($dl);
    if ($dl === '' || preg_match('/^#{1,6}\s/', $dl) || preg_match('/^\|/', $dl) || preg_match('/^[-*_]{3,}$/', $dl) || preg_match('/^```/', $dl)) {
        continue;
    }
    $dl = preg_replace('/\*\*(.+?)\*\*/', '$1', $dl);
    $dl = preg_replace('/\*(.+?)\*/', '$1', $dl);
    if ($pageDescription === '') {
        $pageDescription = $dl;
    } else {
        $pageDescription .= ' ' . $dl;
    }
    if (mb_strlen($pageDescription) >= 130) {
        break;
    }
}
$pageDescription = mb_substr($pageDescription, 0, 160);
if (mb_strlen($pageDescription) < 50) {
    $pageDescription = 'AI-powered data analysis result with tables, charts, and insights. Generated by Statbate Bot for Telegram.';
}
$canonicalUrl = 'https://sum.statbate.com/r/' . $id;
$ogImageUrl = $canonicalUrl . '/og.png';
$pageTitleSafe = htmlspecialchars($pageTitle, ENT_QUOTES, 'UTF-8');
$pageDescSafe = htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8');

/**
 * Convert Markdown to full HTML with proper semantic elements.
 */
function convertMarkdownToHtml(string $text): string
{
    $text = preg_replace("/\r\n|\r/", "\n", $text);

    // Strip HTML tags from AI response (may contain <b>, <i>, etc.) before markdown processing
    $text = strip_tags($text);

    // Extract fenced code blocks
    $codeBlocks = [];
    $text = preg_replace_callback('/```(\w*)\n(.*?)```/su', function ($m) use (&$codeBlocks) {
        $placeholder = '%%CODEBLOCK' . count($codeBlocks) . '%%';
        $lang = $m[1] ?: '';
        $code = htmlspecialchars(trim($m[2]), ENT_QUOTES, 'UTF-8');
        $langAttr = $lang ? ' class="language-' . htmlspecialchars($lang, ENT_QUOTES, 'UTF-8') . '"' : '';
        $codeBlocks[$placeholder] = '<pre><code' . $langAttr . '>' . $code . '</code></pre>';
        return "\n" . $placeholder . "\n";
    }, $text);

    // Extract inline code
    $inlineCodes = [];
    $text = preg_replace_callback('/`([^`\n]+)`/u', function ($m) use (&$inlineCodes) {
        $placeholder = '%%INLINE' . count($inlineCodes) . '%%';
        $inlineCodes[$placeholder] = '<code>' . htmlspecialchars($m[1], ENT_QUOTES, 'UTF-8') . '</code>';
        return $placeholder;
    }, $text);

    // Extract and convert tables
    $tableBlocks = [];
    $lines = explode("\n", $text);
    $result = [];
    $tableBuffer = [];

    foreach ($lines as $line) {
        $trimmed = trim($line);
        if (preg_match('/^\|.+\|$/', $trimmed)) {
            $tableBuffer[] = $trimmed;
        } else {
            if (count($tableBuffer) >= 2) {
                $placeholder = '%%TABLE' . count($tableBlocks) . '%%';
                $tableBlocks[$placeholder] = convertTable($tableBuffer);
                $result[] = $placeholder;
            } elseif (count($tableBuffer) === 1) {
                $result[] = $tableBuffer[0];
            }
            $tableBuffer = [];
            $result[] = $line;
        }
    }
    if (count($tableBuffer) >= 2) {
        $placeholder = '%%TABLE' . count($tableBlocks) . '%%';
        $tableBlocks[$placeholder] = convertTable($tableBuffer);
        $result[] = $placeholder;
    } elseif (count($tableBuffer) === 1) {
        $result[] = $tableBuffer[0];
    }
    $text = implode("\n", $result);

    // Escape HTML in remaining text
    $text = htmlspecialchars($text, ENT_QUOTES, 'UTF-8');

    // Headers — allow optional leading whitespace, handle h1-h6
    $text = preg_replace_callback('/^\s*(#{1,6})\s+(.+)$/mu', function ($m) {
        $level = strlen($m[1]);
        return '<h' . $level . '>' . trim($m[2]) . '</h' . $level . '>';
    }, $text);

    // Bold and italic
    $text = preg_replace('/\*\*(.+?)\*\*/su', '<strong>$1</strong>', $text);
    $text = preg_replace('/(?<!\*)\*([^*\n]+?)\*(?!\*)/u', '<em>$1</em>', $text);

    // Horizontal rules
    $text = preg_replace('/^[\-\*_]{3,}$/mu', '<hr>', $text);

    // Convert list blocks (unordered)
    $text = preg_replace_callback('/(?:^[\-\*]\s+.+$\n?)+/mu', function ($m) {
        $items = preg_replace('/^[\-\*]\s+(.+)$/mu', '<li>$1</li>', trim($m[0]));
        return '<ul>' . $items . '</ul>';
    }, $text);

    // Convert list blocks (ordered)
    $text = preg_replace_callback('/(?:^\d+\.\s+.+$\n?)+/mu', function ($m) {
        $items = preg_replace('/^\d+\.\s+(.+)$/mu', '<li>$1</li>', trim($m[0]));
        return '<ol>' . $items . '</ol>';
    }, $text);

    // Links: [text](url)
    $text = preg_replace('/\[([^\]]+)\]\(([^)]+)\)/', '<a href="$2" target="_blank">$1</a>', $text);

    // Paragraphs: wrap loose text blocks
    $text = preg_replace('/\n{2,}/', "\n\n", $text);
    $blocks = preg_split('/\n\n/', $text);
    $output = [];
    foreach ($blocks as $block) {
        $block = trim($block);
        if ($block === '') continue;
        // Don't wrap blocks that already start with a block-level HTML tag or placeholder
        if (preg_match('/^<(?:h[1-6]|ul|ol|pre|hr|table|blockquote|div)|^%%/', $block)) {
            $output[] = $block;
        } else {
            // Convert single newlines to <br> within paragraphs
            $output[] = '<p>' . str_replace("\n", '<br>', $block) . '</p>';
        }
    }
    $text = implode("\n", $output);

    // Restore placeholders
    $text = str_replace(array_keys($codeBlocks), array_values($codeBlocks), $text);
    $text = str_replace(array_keys($inlineCodes), array_values($inlineCodes), $text);
    $text = str_replace(array_keys($tableBlocks), array_values($tableBlocks), $text);

    return $text;
}

/**
 * Convert a block of Markdown table rows to an HTML <table>.
 */
function convertTable(array $rows): string
{
    $dataRows = [];
    foreach ($rows as $row) {
        // Skip separator rows
        if (preg_match('/^\|[\s\-:|]+\|$/', $row)) {
            continue;
        }
        $cells = array_map('trim', explode('|', trim($row, '|')));
        // Strip markdown bold
        $cells = array_map(function ($c) {
            return preg_replace('/\*\*(.+?)\*\*/', '$1', $c);
        }, $cells);
        $dataRows[] = $cells;
    }

    if (empty($dataRows)) return '';

    $html = '<div class="table-wrap"><table>';

    // First row as header
    $html .= '<thead><tr>';
    foreach ($dataRows[0] as $cell) {
        $html .= '<th>' . htmlspecialchars($cell, ENT_QUOTES, 'UTF-8') . '</th>';
    }
    $html .= '</tr></thead>';

    // Remaining rows as body
    if (count($dataRows) > 1) {
        $html .= '<tbody>';
        for ($i = 1; $i < count($dataRows); $i++) {
            $html .= '<tr>';
            foreach ($dataRows[$i] as $cell) {
                $html .= '<td>' . htmlspecialchars($cell, ENT_QUOTES, 'UTF-8') . '</td>';
            }
            $html .= '</tr>';
        }
        $html .= '</tbody>';
    }

    $html .= '</table></div>';
    return $html;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitleSafe ?> — Statbate Bot</title>
    <meta name="description" content="<?= $pageDescSafe ?>">
    <meta name="robots" content="noindex, nofollow">
    <link rel="canonical" href="<?= $canonicalUrl ?>">

    <!-- Open Graph -->
    <meta property="og:type" content="article">
    <meta property="og:title" content="<?= $pageTitleSafe ?>">
    <meta property="og:description" content="<?= $pageDescSafe ?>">
    <meta property="og:url" content="<?= $canonicalUrl ?>">
    <meta property="og:site_name" content="Statbate Bot">
    <meta property="og:locale" content="en_US">
    <meta property="og:image" content="<?= $ogImageUrl ?>">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:image:type" content="image/png">
    <meta property="article:published_time" content="<?= date('c', filemtime($filePath)) ?>">

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<?= $pageTitleSafe ?>">
    <meta name="twitter:description" content="<?= $pageDescSafe ?>">
    <meta name="twitter:image" content="<?= $ogImageUrl ?>">

    <script defer src="https://u.statbate.com/script.js" data-website-id="1f43d62d-5e94-4ccf-9afa-52900d7e365c"></script>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.65;
            color: #1e293b;
            background: #f1f5f9;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        /* ── Header ── */
        .top-bar {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            color: #fff;
            padding: 1rem 1.5rem;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: 0 2px 12px rgba(0,0,0,0.2);
        }
        .top-bar .brand {
            display: flex;
            align-items: center;
            gap: 0.6rem;
        }
        .top-bar .brand-icon {
            width: 32px;
            height: 32px;
            background: linear-gradient(135deg, #4ade80, #22d3ee);
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1rem;
        }
        .top-bar .brand-text {
            font-size: 1.1rem;
            font-weight: 700;
            letter-spacing: -0.01em;
        }
        .top-bar .brand-text span {
            color: #4ade80;
        }
        .top-bar .meta {
            font-size: 0.75rem;
            color: #94a3b8;
        }

        /* ── Layout ── */
        .page-wrap {
            flex: 1;
            max-width: 1080px;
            width: 100%;
            margin: 0 auto;
            padding: 1.5rem 1rem;
            display: grid;
            grid-template-columns: 1fr 280px;
            gap: 1.5rem;
            align-items: start;
        }

        /* ── Main content card ── */
        .content-card {
            background: #fff;
            border-radius: 12px;
            padding: 2rem 2.2rem;
            box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04);
            min-width: 0;
        }

        /* ── Sidebar ── */
        .sidebar {
            display: flex;
            flex-direction: column;
            gap: 1rem;
            position: sticky;
            top: 1.5rem;
        }

        /* ── Ad Card ── */
        .ad-card {
            background: linear-gradient(145deg, #1a1a2e 0%, #16213e 40%, #1e1145 100%);
            border-radius: 14px;
            padding: 1.5rem;
            color: #fff;
            box-shadow: 0 4px 20px rgba(22, 33, 62, 0.35);
        }
        .ad-card .ad-label {
            font-size: 0.7rem;
            font-weight: 700;
            letter-spacing: 0.12em;
            text-transform: uppercase;
            color: #4ade80;
            margin-bottom: 0.6rem;
        }
        .ad-card .ad-title {
            font-size: 1rem;
            font-weight: 600;
            line-height: 1.4;
            margin-bottom: 1rem;
            color: #e2e8f0;
        }
        .ad-card .ad-cta {
            display: inline-flex;
            align-items: center;
            gap: 0.35rem;
            background: #4ade80;
            color: #0f172a;
            font-weight: 700;
            font-size: 0.9rem;
            padding: 0.6rem 1.3rem;
            border-radius: 8px;
            text-decoration: none;
            transition: background 0.15s, transform 0.1s;
        }
        .ad-card .ad-cta:hover {
            background: #22c55e;
            transform: translateY(-1px);
            text-decoration: none;
        }
        .ad-card .ad-cta svg {
            width: 14px;
            height: 14px;
        }

        /* ── Bottom ad (mobile) ── */
        .ad-bottom {
            display: none;
        }

        /* ── Content typography ── */
        .content-card h1, .content-card h2, .content-card h3, .content-card h4 {
            color: #0f172a;
            margin: 1.4em 0 0.4em;
            line-height: 1.3;
        }
        .content-card > h1:first-child,
        .content-card > h2:first-child,
        .content-card > h3:first-child,
        .content-card > p:first-child {
            margin-top: 0;
        }
        .content-card h1 { font-size: 1.5rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.35em; }
        .content-card h2 { font-size: 1.25rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.25em; }
        .content-card h3 { font-size: 1.1rem; }
        .content-card p { margin: 0.7em 0; }
        .content-card a { color: #2563eb; text-decoration: none; }
        .content-card a:hover { text-decoration: underline; }
        .content-card strong { font-weight: 600; }
        .content-card hr {
            border: none;
            border-top: 1px solid #e2e8f0;
            margin: 1.5em 0;
        }

        /* Tables */
        .table-wrap {
            overflow-x: auto;
            margin: 1em 0;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
        }
        .content-card table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.88rem;
        }
        .content-card thead { background: #1e293b; color: #fff; }
        .content-card th {
            padding: 0.65rem 0.8rem;
            text-align: left;
            font-weight: 600;
            white-space: nowrap;
        }
        .content-card td {
            padding: 0.55rem 0.8rem;
            border-bottom: 1px solid #f1f5f9;
        }
        .content-card tbody tr:nth-child(even) { background: #f8fafc; }
        .content-card tbody tr:hover { background: #eef2ff; }

        /* Code */
        .content-card code {
            background: #f1f5f9;
            padding: 0.12em 0.35em;
            border-radius: 4px;
            font-size: 0.86em;
            font-family: 'SF Mono', 'Fira Code', Consolas, monospace;
            color: #c7254e;
        }
        .content-card pre {
            background: #1e293b;
            color: #e2e8f0;
            padding: 1rem 1.2rem;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1em 0;
            font-size: 0.83rem;
            line-height: 1.55;
        }
        .content-card pre code {
            background: none;
            color: inherit;
            padding: 0;
            border-radius: 0;
            font-size: inherit;
        }

        /* Lists */
        .content-card ul, .content-card ol { margin: 0.7em 0; padding-left: 1.4em; }
        .content-card li { margin: 0.25em 0; }

        /* Blockquote */
        .content-card blockquote {
            border-left: 4px solid #4ade80;
            padding: 0.5em 1em;
            margin: 1em 0;
            background: #f8fafc;
            color: #475569;
            border-radius: 0 6px 6px 0;
        }

        /* ── Footer ── */
        .page-footer {
            text-align: center;
            padding: 1.5rem 1rem;
            color: #94a3b8;
            font-size: 0.75rem;
        }
        .page-footer a { color: #64748b; text-decoration: none; }
        .page-footer a:hover { text-decoration: underline; }

        /* ── Responsive ── */
        @media (max-width: 800px) {
            .page-wrap {
                grid-template-columns: 1fr;
                padding: 1rem 0.75rem;
            }
            .sidebar { display: none; }
            .ad-bottom {
                display: block;
                margin: 0 0.75rem 1rem;
            }
            .content-card {
                padding: 1.4rem 1.2rem;
                border-radius: 10px;
            }
            .content-card h1 { font-size: 1.25rem; }
            .content-card h2 { font-size: 1.1rem; }
            .content-card table { font-size: 0.8rem; }
            .content-card th, .content-card td { padding: 0.4rem 0.5rem; }
        }
    </style>
</head>
<body>

    <div class="top-bar">
        <div class="brand">
            <div class="brand-icon">&#x1F4CA;</div>
            <div class="brand-text"><span>Stat</span>bate <span>Bot</span></div>
        </div>
        <div class="meta"><?= htmlspecialchars($generatedAt, ENT_QUOTES, 'UTF-8') ?> UTC</div>
    </div>

    <div class="page-wrap">
        <div class="content-card">
            <?= $htmlContent ?>
        </div>

        <aside class="sidebar">
            <div class="ad-card">
                <div class="ad-label">Statbate Plus</div>
                <div class="ad-title">Full tip history, chat search, member profiles &amp; more</div>
                <a href="https://plus.statbate.com/" class="ad-cta" target="_blank" rel="noopener">
                    Try Free
                    <svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"/></svg>
                </a>
            </div>
        </aside>
    </div>

    <!-- Mobile ad (shown below content on small screens) -->
    <div class="ad-bottom">
        <div class="ad-card">
            <div class="ad-label">Statbate Plus</div>
            <div class="ad-title">Full tip history, chat search, member profiles &amp; more</div>
            <a href="https://plus.statbate.com/" class="ad-cta" target="_blank" rel="noopener">
                Try Free
                <svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"/></svg>
            </a>
        </div>
    </div>

    <footer class="page-footer">
        Statbate Bot &mdash; <a href="https://plus.statbate.com/">plus.statbate.com</a>
    </footer>

</body>
</html>
